name: Deploy FE

on:
  push:
    branches:
      - "main"

env:
  CI: true
  NODE_VERSION: 16.x
  NEXT_TELEMETRY_DISABLED: 1
  AZURE_SUBSCRIPTION: mr-creative-tech

jobs:
  Build-and-Deploy-FE:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: checkout
        uses: actions/checkout@v2

      - name: set yarn cache dir
        run: echo CACHE_DIR=$(yarn config get cacheFolder) >> $GITHUB_ENV

      - name: cache yarn cache dir
        uses: actions/cache@v2
        with:
          path: ${{ env.CACHE_DIR }}
          key: ${{ runner.os }}-yarn_cache-${{ hashFiles('**/yarn.lock') }}

      - name: env
        run: env
      - name: pwd
        run: pwd

      - name: install
        run: yarn install

      - name: login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: login - prod
        if: ${{ github.ref == 'refs/heads/prod-fe' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: deployment script - dev
        if: ${{ github.ref == 'refs/heads/main' }}
        run: ./infrastructure/blob-deploy-ci.sh dev $AZURE_SUBSCRIPTION

      - name: logout
        if: always()
        run: |
          az logout
